DEFAULT_MAX_DISCOUNT_PERCENTAGE = 15
DEFAULT_DRAFT_REMINDER_DAYS=2
DEFAULT_LEAD_SOURCE = "Website"


ROLE_SALES_MANAGER = "Sales Manager"
ROLE_SALES_USER = "Sales User"
ROLE_ACCOUNT_USER = "Account User"
ROLE_INVENTORY_USER = "Inventory User"
